# Details of a services
---
definition: "./vrs_template.xml"
service:
    - name: cars
      group: cars
      definition: "./cars.vrs"
      workingFolder: ./cars
      configuration:
        listenport: '7001'
      targetedVSE: 
      - VSE
    - name: GetAdress
      group: adress
      workingFolder: ./getAddress
      configuration:
        listenport: '7003'
      targetedVSE: 
      - vse-perf