# Details of a services
---
definition: "./vrs_template.xml"
service:
    - name: search_client
      group: cars
      workingFolder: ./search_client
      configuration:
        listenport: '19001'
      targetedVSE: VSE
      
    - name: search_client_2
      group: cars
      workingFolder: ./search_client
      configuration:
        listenport: '19009'
      targetedVSE: VSE
      
    - name: search_client_3
      group: cars
      workingFolder: ./search_client
      configuration:
        listenport: '19019'
      targetedVSE: VSE
