# Details of a services
---
definition: "./vrs_template.xml"
services:
    - name: cars
      group: cars
      definition: "./cars/cars.vrs"
      workingFolder: ./cars
      capacity: 2
      thinkScale: 100
      executionMode: "LIVE"
      configuration:
        listenport: '7001'
      targetedVSE: 
      - vse-perf