# Details of a services
---
definition: "./vrs_template.xml"
services:
    - name: cars
      group: cars
      definition: "./cars/cars.vrs"
      workingFolder: ./cars
      configuration:
        listenport: '7901'
      targetedVSE: 
      - VSE