# Details of a services
---
definition: "./vrs_template.xml"
service:
    - name: cars
      group: cars
      definition: "./cars.vrs"
      workingFolder: ./cars
      configuration:
        listenport: '7001'
      targetedVSE: VSE
    - name: getAdress
      group: cars
      workingFolder: ./getAddress
      configuration:
        listenport: '19002'
      targetedVSE: VSE
    - name: getAddress2
      group: cars
      workingFolder: ./getAddress2
      type: swagger
      configuration:
        listenport: '19002'
      targetedVSE: VSE