# Details of a services
---
definition: "./vrs_template.xml"
services:
    - name: cars
      group: cars
      definition: "./cars/cars.vrs"
      workingFolder: ./cars
      configuration:
        listenport: '7901'
      targetedVSE: 
      - VSE
    - name: carsV2
      group: carsV2
      definition: "./carsV2/cars.vrs"
      workingFolder: ./cars
      configuration:
        listenport: '7902'
      targetedVSE: 
      - VSE      
    - name: getAddress
      group: getAddress
      definition: "./getAddress/getAddress.vrs"
      workingFolder: ./getAddress
      configuration:
        listenport: '7902'
      targetedVSE: 
      - VSE