# Details of a services
---
definition: "./vrs_template.xml"
service:
    - name: search_client
      group: cars
      workingFolder: ./search_client
      configuration:
        listenport: '19001'
      targetedVSE: VSE
