# Details of a services
---
definition: "./vrs_template.xml"
services:
    - name: cars
      group: cars
      definition: "./cars.vrs"
      workingFolder: ./cars
      capacity: 2
      thinkScale: 100
      executionMode: "LIVE"
      configuration:
        listenport: '7001'
      targetedVSE: 
      - VSE
    - name: cars2
      group: cars
      definition: "./cars.vrs"
      workingFolder: ./cars
      configuration:
        listenport: '7001'
      targetedVSE: 
      - VSE