# Details of a services
---
definition: "./vrs_template.xml"
services:
    - name: cars
      group: cars
      capacity: 15
      thinkScale: 200
      definition: "./cars/cars.vrs"
      workingFolder: ./cars
      configuration:
        listenport: '7901'
      targetedVSE: 
      - vse-perf