# Details of a services
---
definition: "./vrs_template.xml"
services:
    - name: cars
      group: cars
      capacity: 10
      thinkScale: 200
      definition: "./cars/cars.vrs"
      workingFolder: ./cars
      configuration:
        listenport: '7901'
      targetedVSE: 
      - vse-perf
    - name: Home
      group: Vodafone
      definition: "./vodafone_home/vodafone_home.vrs"
      workingFolder: ./vodafone_home
      configuration:
        listenport: '8001'
      targetedVSE: 
      - vse-perf
    - name: Home
      group: Vodafone
      definition: "./vodafone_home/vodafone_home.vrs"
      workingFolder: ./vodafone_home
      configuration:
        listenport: '8002'
      targetedVSE: 
      - VSE
      